[package]
name = "jyt"
description = "Translate between serialized data formats"
version = "0.3.0"
authors = ["Alex Hamlin <alex@alexhamlin.co>"]
edition = "2018"

[dependencies]
memmap2 = "0.2"
serde = "1"
serde-transcode = "1"
serde_json = "1"
serde_yaml = "0.8"
structopt = "0.3"
toml = "0.5"
