[package]
name = "jyt"
description = "Translate between serialized data formats"
version = "0.4.7"
authors = ["Alex Hamlin <alex@alexhamlin.co>"]
edition = "2018"

[dependencies]
atty = "0.2"
memmap2 = "0.2"
serde = "1"
serde-transcode = "1"
serde_json = "1"
serde_yaml = "0.8"

[dependencies.clap]
version = "2"
default-features = false

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.toml]
version = "0.5"
features = ["preserve_order"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
