[package]
name = "recompose"
version = "0.1.0"
authors = ["Alex Hamlin <alex@alexhamlin.co>"]
edition = "2018"

[dependencies]
clap = "2"
serde = "1"
serde-value = "0.5"

[dependencies.serde_any]
version = "0.5"
default-features = false
features = ["json", "yaml", "toml"]
